### ISSUE TITLE
The Knights appear undecided as to CLA signature status...

### ISSUE THREAD

**Issue by doismellburning** [python/the-knights-who-say-ni#170]
Apologies for this issue being a bit sparse on details but I don't have a lot of data I can provide...

In https://github.com/python/peps/pull/851 the Knights correctly flagged it as `CLA not signed`

I subsequently submitted a signed CLA and checked back later with https://check-python-cla.herokuapp.com/ - this confirmed that I was registered as now having signed the CLA, and presumably kicked off a removal of the label by the Knights...only to have them reapply it immediately afterwards (see PR thread linked above)

Looks like the same thing happened to @brettcannon when he manually removed the label.

Funky internal state inconsistency / caching fun perhaps...?

**Comment by Mariatta** [comment]
I'm closing this issue since there is nothing to be fixed from the bot.

As mentioned, you have two options:
- Have the user @mindw to create a bpo account and sign the CLA
- Remove the commit made by @mindw (this commit https://github.com/python/peps/pull/851/commits/2807f75b4e56d8c857903bafde0b927fb6ef85f5), and open a PR containing just your commit.

Thanks.

**Comment by doismellburning** [comment]
Right, thanks. Should I file a separate bug for "The Knights erroneously remove the label" or modify and reopen this one?

**Comment by Mariatta** [comment]
Removal of the label is not errornous, but rather a feature.
It is the simplest way for the bot to recheck the PR's CLA status, and it is how a core dev would have done it. I'm planning to move us to Cla-assistant soon. I don't think it's worth the effort to make changes to this now. Thanks.
