### ISSUE TITLE
Archive the project, add note that it is not used/not maintained anymore

### ISSUE THREAD

**Issue by Mariatta** [python/the-knights-who-say-ni#320]
We are now using cpython-cla-bot for CLA checking. As far as I know, the webhook to the-knights-who-say-ni has been disabled across all repositories.

Perhaps it's time to say goodbye. We can add a note saying that we're no longer maintaining this project, and that this is no longer in use. The heroku webservice can also be removed.

Thank you @the-knights-who-say-ni for your years of service!! (six years!)

**Comment by hugovk** [comment]
So long, and thanks for all the "Ni!" 🖖

**Comment by verhovsky** [comment]
Is cpython-cla-bot closed source? Where do I report an issue with it?

I don't see it
* https://github.com/psf?q=cla&type=all&language=&sort= 
* https://github.com/python?q=cla&type=all&language=&sort=

and there's no links on https://github.com/apps/cpython-cla-bot

**Comment by AlexWaygood** [comment]
> Is cpython-cla-bot closed source?

The source code is currently at https://github.com/ambv/cla-bot, but there are plans to move the source code to a repo in the Python organisation on GitHub

> Where do I report an issue with it?

There's no issue tracker _yet_, because it's currently a fork of https://github.com/edgedb/cla-bot, and forks don't get issue trackers on GitHub. But there'll be an issue tracker soon, once the source code has been moved somewhere better. In the meantime, I think https://discuss.python.org/t/https-github-com-python-is-now-using-a-new-cla-bot/14961 is _probably_ as good a place as any :)

**Comment by merwok** [comment]
> forks don't get issue trackers on GitHub

That’s up to you when you create the fork!

**Comment by brettcannon** [comment]
@ambv you good w/ making this repo be read-only?
