### ISSUE TITLE
Use status checks instead of labels

### ISSUE THREAD

**Issue by dstufft** [python/the-knights-who-say-ni#42]
I think it would be better if this used status checks instead of labels (or at least, in addition to labels). If we're using status checks then we can mandate that status checks are passing prior to landing a PR. In addition, someone has to remember to go looking for the correct label to ensure it is applied, but with a status check, even if we don't mandate it, a failing status check requires additional clicks and "are you sure?"s to actually merge it.

**Comment by brettcannon** [comment]
The problem with a status check is how do you trigger a re-run without synchronizing the PR? The reason every CLA bot seems to use labels is that since CLA signing is out-of-band you can easily deal with it with labels while status checks only execute when there's a code change (from my understanding). Labels also allow for project managers to trigger the update rather than relying on the PR committer to do something to make the check occur again.

**Comment by dstufft** [comment]
@brettcannon There's no reason the bot can't re-update the status when it detects that the CLA has been signed. Status checks don't ever get "executed", it's just a way for external systems to indicate that a particular commit is passing/failing/pending/erroring, though it's common for systems to execute some code that does this check on push/new-pr.

As far as allowing project managers to trigger the update, you could allow a comment from anyone with commit bit on that repository to override the status check or trigger a manual recheck.

**Comment by brettcannon** [comment]
As of right now the bot is entirely stateless with no polling. Detecting that a CLA has been signed will either require a polling of bugs.python.org or setting up some push mechanism on that end. I don't see this feature as important enough to put the work in to make that happen.

We could possibly get away with not storing what PRs need to be checked by querying what PRs have a "CLA not signed" label set on them, but the bot also currently doesn't have a specific whitelist of what repos are using it so that would need to change to know what repositories it needs to care about (it's possible to know [when a team is added to a repo](https://developer.github.com/v3/activity/events/types/#teamaddevent), but [the team API](https://developer.github.com/v3/orgs/teams/) would be needed to query at startup).

As for having a comment trigger the check, that does increase the amount of data being sent and potential complexity of parsing those messages, but that's obviously a very minor complaint.

And so I don't have to find it again, the Statuses API is documented at https://developer.github.com/v3/repos/statuses/ . Since you can only add statuses and not update them in-place I think the `target_url` needs to be consistent.

**Comment by brettcannon** [comment]
If we make the CLA status required, I can see it worth putting in the effort to making this happen. As I said previously, though, the trick is to figure out how to manually trigger a CLA check. I see two solutions to this.

One is to provide a "Details" link which provides a page to do the check and then any details as to why the CLA check comes back as failing. My worry with this approach is crawlers, etc. leading to unnecessary churn on the bot and bugs.python.org from doing unnecessary checks. There could be a "Re-Check" button the page to trigger the actual check.

The second option is to provide a "CLA check" label which the bot uses as a trigger to do the check. The bot could then remove the label after updating the status. Since labels are not usable by people without write access that keeps the traffic down as well as the complexity as it means not having to create some user-visible page that needs to be maintained, tested in various browsers, etc. (In this instance the "Details" link would point to the comment that the bot left on the issue.)

I don't like a comment solution as that just adds unnecessary noise in the PR comment history that you have to constantly overlook without going back and deleting the comment (which the bot could do). The other issue is you have to remember the bot trigger syntax where with a label you just need to remember there's a relevant label to flip on.

**Comment by dstufft** [comment]
Closing and re-opening a PR re-sends the webhook normally.

**Comment by brettcannon** [comment]
Yep, that would trigger it again as well, although I wonder if that would be noisier than a label change? Plus would that re-trigger Travis and AppVeyor as well?

**Comment by dstufft** [comment]
Yes it would retry everything. The flip side is that PR authors can do it themselves rather than needing someone with commit bit to do it for them. 

I wonder if bpo could fire a webhook when someone's CLA status changes or they change the associated GitHub user with their account. If it did that then it could remain stateless and just listen for those events as well.

**Comment by brettcannon** [comment]
With enough effort b.p.o could hit some endpoint to trigger a recheck.

**Comment by dstufft** [comment]
That seems like a sort of ultimate solution here, requiring no additional effort from either committers or contributors on a day to day basis.

**Comment by brettcannon** [comment]
Ultimate solution, but also the most amount of work 😜

**Comment by dstufft** [comment]
Pfft, it's just a simple matter of programming.

**Comment by brettcannon** [comment]
Latest thinking:

* CLA bot sets status as "pending"
* Do the status check
* If good, then set status to "success"
* If failed, then set status to "failure" and ...
  - Specify which usernames weren't found in the description
  - Specify which usernames have not signed the CLA in the description
  - Set the Details link to the devguide's instructions on how to solve this

The context can be "check CLA". An equivalent "check CLA" label can be used to manually trigger a check or to flag that something went wrong with the CLA bot in case a manual check needs to be done.

**Comment by dstufft** [comment]
If it's a mandatory check then it will start out as pending. FWIw I did something similar with: https://github.com/pypa/browntruck/blob/master/browntruck.py (which was for requiring news files, but same idea). I also had it accept and override label too.

**Comment by brettcannon** [comment]
@dstufft Right, forgot about the pending bit when required (I guess the question is whether we can assume everyone using the bot will make it required?).

The other thing I realized is whether a comment is still necessary on new PRs. My suspicion is yes as GitHub doesn't trigger a message for statuses and people will probably not notice the failed status otherwise (but the message could be as simple as "see the 'check CLA' status for more details."

**Comment by hugovk** [comment]
Closing because the Knights have been replaced by [the CLA bot](https://github.com/apps/cpython-cla-bot#-who-says-ekke-ekke-ekke-ekke-ptang-zoom-boing). See [the discussion](https://discuss.python.org/t/14961) for more details.

https://github.com/python/the-knights-who-say-ni/pull/326
